sonar.projectKey=SuppieRK_eft-sherpa-bot
sonar.organization=suppierk
sonar.projectName=eft-sherpa-bot

sonar.sources=src,scripts,.github
sonar.tests=test,benchmark
sonar.exclusions=src/worker-configuration.d.ts
sonar.coverage.exclusions=scripts/**,.github/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
